#!/bin/bash

i3path=${HOME}/.config/i3
conf=${i3path}/config
theme="$1"

if [ -z "$theme" ]; then
	echo "Error: provide an i3 theme"
	exit
fi

fpath="${i3path}/themes/base16-i3/colors/base16-${theme}.config"
if [ ! -f "$fpath" ]; then
	echo "Error: unable to find $theme files"
	exit
fi

cat $i3path/base.config > $conf
sed -e '/#{{colors}}/ {' -e "r $fpath" -e 'd' -e '}' -i $conf
i3-msg "reload" 2>&1 1>/dev/null
