[main]
color-tsharks = ['/usr/bin/tshark']
column-format = ['%m', 'No.', 'true', '%t', 'Time', 'true', '%s', 'Source', 'true', '%d', 'Dest', 'true', '%p', 'Proto', 'true', '%L', 'Length', 'true', '%i', 'Info', 'true', '%Cus:dns.ptr.domain_name:0:R', 'Domain Name', 'true']
column-format-bak = ['%m', 'No.', 'true', '%t', 'Time', 'true', '%s', 'Source', 'true', '%d', 'Dest', 'true', '%p', 'Proto', 'true', '%L', 'Length', 'true', '%i', 'Info', 'true']
key-mappings = ['l <Right>', 'h <Left>']
last-used-tshark = '/usr/bin/tshark'
layout = 'altview2'
packet-colors = true
recent-filters = ['mdns', 'mdns && ipv6', 'mdns && ip']
validated-tsharks = ['/usr/bin/tshark']

