#!/bin/sh

usage() {
	echo "usage: $(basename $0) [-h] <command>"
	echo ""
	echo "  -h  display this help and exit"
	echo ""
	echo "There are only two commands:"
	echo "  pull   Pull configuration data from cloud"
	echo "  push	Push configuration data to cloud"
}

pull() {
	# pull from git
	git pull origin 

	# copy files
	cp bashrc $HOME/.bashrc
	cp vimrc $HOME/.vimrc
	cp vim $HOME/.vim -Rf
	cp gitconfig $HOME/.gitconfig
	cp git-completion.bash $HOME/.git-completion.bash
}

push() {
	cp $HOME/.bashrc bashrc
	cp $HOME/.vimrc vimrc
	cp $HOME/.vim vim -Rf
	cp $HOME/.gitconfig gitconfig
	cp $HOME/.git-completion.bash git-completion.bash

	# save them to git
	# git add -u
	# git commit -m "snapshot at $(date '+%F %H:%M')"
	# git push origin master
}


while :; do
	case $1 in
		-h|-\?|--help)
			usage	
			exit
			;;
		pull)
			pull
			exit
			;;
		push)
			push
			exit
			;;
		*)
			echo "Error: Unknown command. Use $(basename $0) -h for help"
			break
	esac
done
