#!/bin/sh

usage() {
	echo "usage: $(basename $0) [-h] <command>"
	echo ""
	echo "  -h  display this help and exit"
	echo ""
	echo "There are only two commands:"
	echo "  pull   Pull configuration data from cloud"
	echo "  update Update the current directory with the files/directories from the system"	
}

pull() {
	# copy files
	cp bashrc $HOME/.bashrc
	cp vimrc $HOME/.vimrc
	cp vim $HOME/.vim -TRf
	cp gitconfig $HOME/.gitconfig
	cp git-completion.bash $HOME/.git-completion.bash
}

update() {
	cp $HOME/.bashrc bashrc
	cp $HOME/.vimrc vimrc
	cp $HOME/.vim vim -TRf
	cp $HOME/.gitconfig gitconfig
	cp $HOME/.git-completion.bash git-completion.bash

	# save them to git
	# git add -u
	# git commit -m "snapshot at $(date '+%F %H:%M')"
	# git push origin master
}

# if no argument ring usage
if [ -z "$1" ];
then
	usage
	exit
fi


while :; do
	case $1 in
		-h|-\?|--help)
			usage	
			exit
			;;
		pull)
			pull
			exit
			;;
		update)
			update
			exit
			;;
		*)
			echo "Error: Unknown command. Use $(basename $0) -h for help"
			break
	esac
done
