#!/bin/bash

function process {
    target=$1

    src="$HOME/.${target}"
    dst="`pwd`/${target}"

    if [ -L $src ]; then
        unlink $src
    elif [ -f $src ]; then
        rm $src
    elif [ -d $src ]; then
        rm -Rf $src
    fi

    ln -s $dst $src
    printf "%-20s -> dotfiles/${target}\n" "~/.${target}"
}

process vimrc
process vim
# process bashrc
# process bash_profile
# process git-completion.bash
# process tmux.conf
# process bin
# process gitconfig
# process gdbinit
process config/nnn
process config/nvim
# process xinitrc
# process config/i3
# process config/i3status
# process config/kitty
