#!/bin/bash

tpath=${HOME}/.config/termite
conf=${tpath}/config
theme="$1"

if [ -z "$theme" ]; then
	echo "Error: provide a theme"
	exit
fi

fpath="${tpath}/themes/base16-termite/themes/base16-$theme.config"
if [ ! -f "$fpath" ]; then
	echo "Error: unable to find $theme files"
	exit
fi

cat $tpath/base.config > $conf
cat $fpath >> $conf
killall -USR1 termite
